GH actions, take 2

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,12 +1,11 @@
-name: Compile IE, run unit tests and check that all generated data is present
+name: Check that generated data is up to date and update icons for web manual
 
-# Run on PRs on every update
+# TODO make sure that PRs can't ever overwrite the main icons
 on:
-  pull_request:
   push:
 
 jobs:
-  run:
+  test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -24,6 +23,45 @@ jobs:
         with:
           java-version: 17
       - name: Compile IE
-        run: ./gradlew --max-workers 1 compileJava
+        run: ./gradlew compileJava
       - name: Run unit tests
-        run: ./gradlew --max-workers 1 test
+        run: ./gradlew test
+  datagen:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/cache@v2
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+            build/fg_cache
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
+      - name: Set up JDK 17
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17
+      - uses: openrndr/setup-opengl@v1.1
+      # From https://github.com/jyapayne/nim-staticglfw/blob/d270e2b9fb5472bf87338aee80c00105fa957332/.github/workflows/build.yml
+      # TODO figure out which ones we actually need
+      - name: Install GUI
+        run: |
+          sudo apt update
+          sudo apt install -y  build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb libllvm6.0
+      - name: Create list of existing generated resources
+        run: find src/generated/resources/ ! -path "**/.cache*" > resources.txt
+      - name: Run data generation
+        # Hide the non-zero return code from gradle. runData always returns !=0 (to stop gradle from "caching" it?)
+        run: xvfb-run --auto-servernum ./gradlew runData || true
+      - name: Check for crashes during data generation
+        run: bash -c "[ -f run/ie_data_gen_done ]"
+      - name: Check that no files have changed
+        # TODO --exit-code doesn't seem to be working as advertised?
+        run: git update-index --really-refresh && git diff-index --ignore-all-space HEAD && git diff-index --ignore-all-space --quiet HEAD || (git diff && false)
+      - name: Create list of actual generated resources
+        run: find src/generated/resources/ ! -path "**/.cache*" > resources_new.txt
+      - name: Check that no new resources have been created
+        run: diff resources.txt resources_new.txt
